version: '3'

services:
  animeloop-api:
    container_name: animeloop-api
    build:
      context: .
      dockerfile: ./Dockerfile.node
    ports:
      - 7775:7775
    networks:
      - postgres_default
      - redis_default
    volumes:
      - node_modules:/usr/src/app/node_modules
      - dist:/usr/src/app/dist
    command: yarn start:api
  animeloop-twitterbot:
    container_name: animeloop-twitterbot
    build:
      context: .
      dockerfile: ./Dockerfile.node
    networks:
      - postgres_default
      - redis_default
    volumes:
      - node_modules:/usr/src/app/node_modules
      - dist:/usr/src/app/dist
    command: yarn start:twitterbot
  animeloop-telegrambot:
    container_name: animeloop-telegrambot
    build:
      context: .
      dockerfile: ./Dockerfile.node
    networks:
      - postgres_default
      - redis_default
    volumes:
      - node_modules:/usr/src/app/node_modules
      - dist:/usr/src/app/dist
    command: yarn start:telegrambot
  # animeloop-automator:
  #   container_name: animeloop-automator
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.automator
  #   networks:
  #     - postgres_default
  #     - redis_default
  #   command: yarn start:automator
volumes:
  node_modules:
  dist:
networks:
  postgres_default:
    external: true
  redis_default:
    external: true