version: '3'

services:
  animeloop-twitterbot:
    container_name: animeloop-twitterbot
    build:
      context: .
      dockerfile: ./Dockerfile-node
    networks:
      - postgres_default
      - redis_default
    command: yarn start:twitterbot
networks:
  postgres_default:
    external: true
  redis_default:
    external: true