name: TSLint

on: [pull_request]

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v1
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Install
        run: yarn install
      - name: Lint
        uses: shincurry/tslint-actions@test
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '*.ts'
